const GameData = {
   cathegories: [
    {
        name: "Countries",
        tasks: [
            "WIELKA BRYTANIA",
            "PAPUA NOWA GWINEA",
            "MACEDONIA",
            "BURKINA FASO",
            "IRAN",
            "MAURETANIA",
            "KANADA",
            "JAPONIA",
            "CHIŃSKA REPUBLIKA LUDOWA",
            "PERU",
            "SALWADOR",
            "BOŚNIA I HERCEGOWINA",
            "ARABIA SAYDYJSKA",
            "PAKISTAN",
            "REPUBLIKA POŁUDNIOWEJ AFRYKI",
            "RWANDA",
            "HISZPANIA",
            "IRLANDIA PÓŁNOCNA",
            "SUDAN POŁUDNIOWY",
            "KIRGISTAN",
        ],
    },
    {
        name: "Movies",
        tasks: [
            "SKAZNI NA SHAWSHANK",
            "ZEMSTA REWOLWEROWCA",
            "SZYBCY I WŚCIEKLI",
            "ZOMBIELAND",
            "POWRÓT ŻYWYCH TRUPÓW",
            "ROZWAŻNA I ROMANTYCZNA",
            "THOR MIŁOŚĆ I GROM",
            "MIŁOŚĆ SZMARAGD I KROKODYL",
            "KULOODPORNY MNICH",
            "PRZYCZAJONY TYGRYS UKRYTY SMOK",
            "ARMAGEDDON",
            "NIESAMOWITY SPIDER MAN",
            "MROCZNY RYCERZ",
            "KARATE KID",
            "KRWAWY SPORT",
            "HARRY POTTER I KOMNATA TAJEMNIC",
            "RAMBO PIERWSZA KREW",
            "WEJŚCIE SMOKA",
            "FORREST GUMP",
            "KEVIN SAM W DOMU",
        ]
    },
    {
        name: "Tv Series",
        tasks: [
            "MODA NA SUKCES",
            "PRZYJACIELE",
            "TRZECIA PLANETA OD SŁOŃCA",
            "DYNASTIA",
            "THE WALKING DEAD",
            "GRA O TRON",
            "DOMEK Z KART",
            "NA WSPÓLNEJ",
            "PIERWSZA MIŁOŚĆ",
            "M JAK MIŁOŚĆ",
            "NA DOBRE I NA ZŁE",
            "KLAN",
            "PLEBANIA",
            "NIEWOLNICA IZAURA",
            "DR QUINN",
        ]
    },
    {
        name: "Person",
        tasks: [
            "PERSONA NON GRATA",
            "ARTYSTA PLASTYK",
            "SENIOR FRONTEND DEVELOPER",
            "LUMP",
            "PREZES PARTII",
            "MISTRZ OLIMPIJSKI W RZUCIE MŁOTEM",
            "DOKTOR NAUK MEDYCZNYCH",
            "DYREKTOR SZKOŁY",
            "STRÓŻ PRAWA",
            "TRENER PERSONALNY",
            "STRAŻAK",
            "KIEROWNIK BUDOWY",
            "SPRZEDAWCA WARZYW",
            "BRAMKARZ REPREZENTACJI",
            "SERWISANT ROWERÓW",
            "KIEROWCA RAJDOWY",
            "SZEF KUCHNI",
            "STRAŻNIK GRANICZNY",
            "ZAWODOWY GRACZ",
            "MECHANIK SAMOCHODOWY",
            "KIEROWCA AUTOBUSU",
        ]
    }
   ]
   
}

export default GameData;